services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-8060}:${HOST_PORT:-8060}"
    volumes:
      - ./frontend:/frontend
      - ./.env:/frontend/.env
      - /frontend/node_modules