services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${HOST_PORT:-8060}:${HOST_PORT:-8060}"
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${VITE_API_PORT:-8050}:${VITE_API_PORT:-8050}"
    env_file:
      - .env
    volumes:
      - shared_gen:/shared_gen
  
  queue_db:
    image: redis:7
    container_name: queue_db
    ports:
      - "6379:6379"
  
  worker_generate:
    build: 
      context: ./worker_generate
      dockerfile: Dockerfile
    container_name: worker_generate
    ports:
      - "${WG_PORT:-8040}:${WG_PORT:-8040}"
    env_file:
      - .env
    volumes:
      - ./worker_generate:/worker_generate
      - shared_gen:/shared_gen

volumes:
  shared_gen: